/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animewatchlistmanager;

/**
 *
 * @author ljlosa
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;
public class AddNew extends javax.swing.JFrame {

    /**
     * Creates new form AddNew
     */
    private int userId;
    public WatchlistDashboard dashboard;
    public AddNew(WatchlistDashboard dashboard, int userId) {
        initComponents();
        this.userId = userId;
        this.dashboard = dashboard;
        AppIcon.setAppIcon(this);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtGenre = new javax.swing.JTextField();
        txtEpisodes = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtRating = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Anime");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Add new anime");

        txtTitle.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTitleMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTitleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTitleMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtTitleMouseReleased(evt);
            }
        });
        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });

        txtGenre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtGenre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGenreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtGenreMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtGenreMousePressed(evt);
            }
        });

        txtEpisodes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtEpisodes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEpisodesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEpisodesMousePressed(evt);
            }
        });

        cmbStatus.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select status", "Watching", "Completed", "On Hold", "Dropped", "Plan to Watch" }));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Rating");

        txtRating.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtRating.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRatingMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtRatingMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("e.g. 4.9");

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Title");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Genre");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Episode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(txtTitle)
                            .addComponent(txtGenre)
                            .addComponent(txtEpisodes)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEpisodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String title = txtTitle.getText();
        String genre = txtGenre.getText();
        String episodes = txtEpisodes.getText();
        String status = cmbStatus.getSelectedItem().toString();
        String rating = txtRating.getText();
        String username = "SELECT INTO users WHERE username";
        
        if (title.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Title cannot be empty!");
            return;
        }
        try (Connection conn = DBConnection.connect()) {
            String sql = "INSERT INTO watchlist (user_id, title, genre, episodes, status, rating) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, userId);
            pst.setString(2, title);
            pst.setString(3, genre);
            pst.setInt(4, Integer.parseInt(episodes));
            pst.setString(5, status);
            pst.setDouble(6, Double.parseDouble(rating));
            pst.executeUpdate();
            
            ActivityLogger.log(userId, username, "Deleted anime: " + title);
            JOptionPane.showMessageDialog(this, "Anime added successfully!");
            dashboard.loadAnimeList(); // refresh table in WatchlistDashboard
            this.dispose(); // close Add frame
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void txtTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTitleMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtTitleMouseClicked

    private void txtGenreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGenreMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtGenreMouseClicked

    private void txtEpisodesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEpisodesMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEpisodesMouseClicked

    private void txtRatingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRatingMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtRatingMouseClicked

    private void txtTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTitleMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtTitleMousePressed

    private void txtGenreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGenreMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtGenreMouseEntered

    private void txtGenreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGenreMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtGenreMousePressed

    private void txtEpisodesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEpisodesMousePressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtEpisodesMousePressed

    private void txtRatingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRatingMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRatingMousePressed

    private void txtTitleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTitleMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTitleMouseExited

    private void txtTitleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTitleMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTitleMouseReleased

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEpisodes;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
