/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animewatchlistmanager;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import java.sql.*;
import java.util.Vector;

/**
 *
 * @author ljlosa
 */
public class AdminAnimeRequests extends javax.swing.JFrame {

    /**
     * Creates new form AdminAnimeRequests
     */
   
    public AdminAnimeRequests() {
        initComponents();
        loadRequests("pending", tblPending);
        loadRequests("approved", tblApproved);
        loadRequests("rejected", tblRejected);
       
    }
    
    private void loadRequests(String status, JTable table) {
        
    try (Connection conn = DBConnection.connect()) {
        String sql = "SELECT ar.user_id, u.username, ar.title, ar.comment, ar.status, ar.created_at " +
             "FROM anime_requests ar " +
             "JOIN users u ON ar.user_id = u.user_id " +
             "WHERE ar.status = ? " +
             "ORDER BY ar.created_at DESC";

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, status);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("user_id"),
                rs.getString("username"),
                rs.getString("title"),
                rs.getString("comment"),
                rs.getString("status"),
                rs.getString("created_at")
            });
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    private void updateRequestStatus(int id, String status) {
    try (Connection conn = DBConnection.connect()) {
        String sql = "UPDATE anime_requests SET status=? WHERE id=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, status);
        ps.setInt(2, id);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Request " + status + "!");
        loadRequests("pending", tblPending);
        loadRequests("approved", tblApproved);
        loadRequests("rejected", tblRejected);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    
       


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPending = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblApproved = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRejected = new javax.swing.JTable();
        btnApproved = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPending.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Requested Anime", "Comment", "Status", "Requested Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPending);
        tblPending.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("Anime Request", jScrollPane1);

        tblApproved.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Approved Anime", "Comment", "Status", "Approved Time"
            }
        ));
        jScrollPane2.setViewportView(tblApproved);

        jTabbedPane1.addTab("Approved", jScrollPane2);

        tblRejected.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Rejected Anime", "Comment", "Status", "Rejected Time"
            }
        ));
        jScrollPane3.setViewportView(tblRejected);

        jTabbedPane1.addTab("Rejected", jScrollPane3);

        btnApproved.setText("Approve");
        btnApproved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovedActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        jButton3.setText("Refresh");

        jButton4.setText("Upload anime");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Upload Episode");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(568, 568, 568)
                        .addComponent(btnApproved)
                        .addGap(18, 18, 18)
                        .addComponent(btnReject)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(27, 27, 27)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReject)
                    .addComponent(btnApproved)
                    .addComponent(btnDelete))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Anime Requests");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnApprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovedActionPerformed
        // TODO add your handling code here:
        
         int row = tblPending.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a request first!");
            return;
        }

        int userId = Integer.parseInt(tblPending.getValueAt(row, 0).toString());
        String title = tblPending.getValueAt(row, 2).toString();

        try (Connection conn = DBConnection.connect()) {
            String sql = "UPDATE anime_requests SET status='approved' WHERE user_id=? AND title=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, userId);
            ps.setString(2, title);

            int updated = ps.executeUpdate();
            if (updated > 0) {
                String notifSql = "INSERT INTO notifications (user_id, message) VALUES (?, ?)";
                PreparedStatement notifPs = conn.prepareStatement(notifSql);
                notifPs.setInt(1, userId);
                notifPs.setString(2, "✅ Your anime request '" + title + "' has been approved!");
                notifPs.executeUpdate();

                JOptionPane.showMessageDialog(this, "Request approved & user notified!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to approve request.");
            }

            loadRequests("pending", tblPending);
            loadRequests("approved", tblApproved);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnApprovedActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        int row = tblPending.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a request first!");
            return;
        }

        // ✅ Corrected column indexes
        int userId = Integer.parseInt(tblPending.getValueAt(row, 0).toString()); // user_id
        String title = tblPending.getValueAt(row, 2).toString(); // title

        try (Connection conn = DBConnection.connect()) {
            // ❌ Update status to "rejected"
            String sql = "UPDATE anime_requests SET status='rejected' WHERE user_id=? AND title=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, userId);
            ps.setString(2, title);

            int updated = ps.executeUpdate();

            if (updated > 0) {
                // 🔔 Add notification for user
                String notifSql = "INSERT INTO notifications (user_id, message) VALUES (?, ?)";
                PreparedStatement notifPs = conn.prepareStatement(notifSql);
                notifPs.setInt(1, userId);
                notifPs.setString(2, "❌ Your anime request '" + title + "' has been rejected.");
                notifPs.executeUpdate();

                JOptionPane.showMessageDialog(this, "Request rejected & user notified!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to reject request.");
                return;
            }

            // 🔄 Refresh tables
            loadRequests("pending", tblPending);
            loadRequests("rejected", tblRejected);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_btnRejectActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblApproved.getSelectedRow();
        if (selectedRow != -1) {
            int requestId = (int) tblApproved.getValueAt(selectedRow, 0);
            String title = tblApproved.getValueAt(selectedRow, 2).toString();
            AdminUploadAnime uploadFrame = new AdminUploadAnime(requestId, title);
            uploadFrame.setVisible(true);
        }
        else {
            new AdminUploadAnime().setVisible(true);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          new AdminUploadEpisode().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         JTable targetTable = null;
        String tableType = "";

        // 🧩 Determine which table has a selected row
        if (tblPending.getSelectedRow() != -1) {
            targetTable = tblPending;
            tableType = "pending";
        } else if (tblApproved.getSelectedRow() != -1) {
            targetTable = tblApproved;
            tableType = "approved";
        } else if (tblRejected.getSelectedRow() != -1) {
            targetTable = tblRejected;
            tableType = "rejected";
        }

        if (targetTable == null) {
            JOptionPane.showMessageDialog(this, "Select a request to delete!");
            return;
        }

        int row = targetTable.getSelectedRow();
        int requestId = (int) targetTable.getValueAt(row, 0);

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this request?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try (Connection conn = DBConnection.connect()) {
            // 🗑️ Delete request from database
            String sql = "DELETE FROM anime_requests WHERE user_id=? AND title=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, (int) targetTable.getValueAt(row, 0)); // user_id
            ps.setString(2, targetTable.getValueAt(row, 2).toString()); // title

            int deleted = ps.executeUpdate();

            if (deleted > 0) {
                JOptionPane.showMessageDialog(this, "Request deleted successfully!");
                // 🔁 Refresh all tables to keep in sync
                loadRequests("pending", tblPending);
                loadRequests("approved", tblApproved);
                loadRequests("rejected", tblRejected);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete request. It may not exist.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAnimeRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAnimeRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAnimeRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAnimeRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAnimeRequests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproved;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblApproved;
    public javax.swing.JTable tblPending;
    private javax.swing.JTable tblRejected;
    // End of variables declaration//GEN-END:variables
}
