/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animewatchlistmanager;

/**
 *
 * @author ljlosa
 */
import java.sql.*;
import javax.swing.*;
public class SystemOverview extends javax.swing.JFrame {

    /**
     * Creates new form SystemOverview
     */
    public SystemOverview() {
        initComponents();
        loadSystemOverview();
    }

     private void loadSystemOverview() {
        try (Connection con = DBConnection.connect()) {
            // Total Users
            PreparedStatement pstUsers = con.prepareStatement("SELECT COUNT(*) AS total FROM users");
            ResultSet rsUsers = pstUsers.executeQuery();
            if (rsUsers.next()) {
                lblUsersCount.setText("Total Users: "  + rsUsers.getString("total"));
            }

            // Total Anime
            PreparedStatement pstAnime = con.prepareStatement("SELECT COUNT(*) AS total FROM watchlist");
            ResultSet rsAnime = pstAnime.executeQuery();
            if (rsAnime.next()) {
                lblAnimeCount.setText("Total Anime: " + rsAnime.getString("total"));
            }

            // Total Messages
            PreparedStatement pstMsg = con.prepareStatement("SELECT COUNT(*) AS total FROM messages");
            ResultSet rsMsg = pstMsg.executeQuery();
            if (rsMsg.next()) {
                lblMessagesCount.setText("Total Messages: " + rsMsg.getString("total"));
            }

            // Total Activity Logs
            PreparedStatement pstLogs = con.prepareStatement("SELECT COUNT(*) AS total FROM activity_logs");
            ResultSet rsLogs = pstLogs.executeQuery();
            if (rsLogs.next()) {
                lblLogsCount.setText("Total Logs: " + rsLogs.getString("total"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading overview: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        lblUsersCount = new javax.swing.JLabel();
        lblAnimeCount = new javax.swing.JLabel();
        lblMessagesCount = new javax.swing.JLabel();
        lblLogsCount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblUsersCount.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblUsersCount.setText("Total Users:");

        lblAnimeCount.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblAnimeCount.setText("Total Anime:");

        lblMessagesCount.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMessagesCount.setText("Total Messages:");

        lblLogsCount.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblLogsCount.setText("Total Logs:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogsCount)
                    .addComponent(lblMessagesCount)
                    .addComponent(lblAnimeCount)
                    .addComponent(lblUsersCount))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblUsersCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAnimeCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMessagesCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogsCount)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("System Overview");

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setText("Refresh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnimeCount;
    private javax.swing.JLabel lblLogsCount;
    private javax.swing.JLabel lblMessagesCount;
    private javax.swing.JLabel lblUsersCount;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
