/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animewatchlistmanager;

/**
 *
 * @author ljlosa
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
public class UserNotificationsFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserNotificationsFrame
     */
    private int currentUserId;
    public UserNotificationsFrame(int userId) {
        initComponents();
        this.currentUserId = userId;
        loadNotifications();
    }
    private void loadNotifications() {
    try (Connection conn = DBConnection.connect()) {
        String sql = "SELECT message, created_at FROM notifications WHERE user_id = ? ORDER BY created_at DESC";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, currentUserId);
        ResultSet rs = ps.executeQuery();

        // 🧩 Update table model with two columns: Message + Added At
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"Message", "Added at"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        int count = 0; // limit toast spam

        while (rs.next()) {
            String message = rs.getString("message");
            Timestamp timestamp = rs.getTimestamp("created_at");

            // Format date/time for readability (e.g., "Nov 5, 2025 10:43 PM")
            String formattedDate = new java.text.SimpleDateFormat("MMM dd, yyyy hh:mm a").format(timestamp);

            model.addRow(new Object[]{ message, formattedDate });

            // 🔔 Show toast for the first 3 notifications only
            if (count < 3) {
                NotificationUtil.showToast(message);
            }
            count++;
        }

        tblNotifications.setModel(model);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading notifications: " + e.getMessage());
    }
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNotifications = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnClearNotif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblNotifications.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Message", "Date and Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblNotifications.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNotificationsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNotifications);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnClearNotif.setText("Clear all notifications");
        btnClearNotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearNotifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClearNotif)
                .addGap(331, 331, 331))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnClearNotif))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblNotificationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNotificationsMouseClicked
      
    }//GEN-LAST:event_tblNotificationsMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnClearNotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearNotifActionPerformed
        // TODO add your handling code here:
         int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to clear all notifications?",
                "Confirm Clear", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection conn = DBConnection.connect()) {
                String sql = "DELETE FROM notifications WHERE user_id = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, currentUserId);
                int deleted = ps.executeUpdate();

                if (deleted > 0) {
                    JOptionPane.showMessageDialog(this, "✅ All notifications cleared!");
                } else {
                    JOptionPane.showMessageDialog(this, "No notifications to clear.");
                }

                loadNotifications(); // Refresh the table

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error clearing notifications: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnClearNotifActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearNotif;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNotifications;
    // End of variables declaration//GEN-END:variables
}
